Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -20,65 +20,65 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
-  lint:
-    runs-on: ubuntu-latest
-    timeout-minutes: 30
-    steps:
-      - name: Checkout current branch
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      - name: Setup Scala and Java
-        uses: actions/setup-java@v4
-        with:
-          distribution: "temurin"
-          java-version: "17"
-      - name: Cache scala dependencies
-        uses: coursier/cache-action@v6
-      - name: Setup proto and moon toolchains
-        uses: moonrepo/setup-toolchain@v0.3.1
-        with:
-          auto-install: true
+  # lint:
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 30
+  #   steps:
+  #     - name: Checkout current branch
+  #       uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 0
+  #     - name: Setup Scala and Java
+  #       uses: actions/setup-java@v4
+  #       with:
+  #         distribution: "temurin"
+  #         java-version: "17"
+  #     - name: Cache scala dependencies
+  #       uses: coursier/cache-action@v6
+  #     - name: Setup proto and moon toolchains
+  #       uses: moonrepo/setup-toolchain@v0.3.1
+  #       with:
+  #         auto-install: true
             
-      - name: Install tooling
-        run: |
-          ./build.sh install
-      - name: Lint code
-        run: ./build.sh lint
+  #     - name: Install tooling
+  #       run: |
+  #         ./build.sh install
+  #     - name: Lint code
+  #       run: ./build.sh lint
 
-  test-js:
-    runs-on: ubuntu-latest
-    timeout-minutes: 30
-    strategy:
-      fail-fast: false
-      matrix:
-        java: ["11"] # Note there is no need ro actually run this for multiple JVM versions for JS
-        scala: ["2.13.13", "3.3.3"]
-    steps:
-      - name: Checkout current branch
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      - name: Setup Scala and Java
-        uses: actions/setup-java@v4
-        with:
-          distribution: "temurin"
-          java-version: ${{ matrix.java }}
-      - name: Cache scala dependencies
-        uses: coursier/cache-action@v6
+  # test-js:
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 30
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       java: ["11"] # Note there is no need ro actually run this for multiple JVM versions for JS
+  #       scala: ["2.13.13", "3.3.3"]
+  #   steps:
+  #     - name: Checkout current branch
+  #       uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 0
+  #     - name: Setup Scala and Java
+  #       uses: actions/setup-java@v4
+  #       with:
+  #         distribution: "temurin"
+  #         java-version: ${{ matrix.java }}
+  #     - name: Cache scala dependencies
+  #       uses: coursier/cache-action@v6
 
-      - name: Run JS tests
-        run: |
-          ./mill -i -k -j 0 "morphir[${{matrix.scala}}].__.js.__.compile" + "morphir[${{matrix.scala}}].__.js.publishArtifacts" + "morphir[${{matrix.scala}}].__.js.__.test"
+  #     - name: Run JS tests
+  #       run: |
+  #         ./mill -i -k -j 0 "morphir[${{matrix.scala}}].__.js.__.compile" + "morphir[${{matrix.scala}}].__.js.publishArtifacts" + "morphir[${{matrix.scala}}].__.js.__.test"
 
-      - name: Cache JS build output
-        # when in master repo: all commits to main branch and all additional tags
-        if: github.ref == 'refs/heads/main' || (github.ref != 'refs/heads/main' && startsWith( github.ref, 'refs/tags/') )
-        uses: actions/cache/save@v4
-        with:
-          path: |
-            out/morphir/${{matrix.scala}}/**/js/
-          key: ${{ runner.os }}-mill-js-${{matrix.java}}-${{ matrix.scala }}-${{ github.sha}}-${{ hashFiles('out') }}
+  #     - name: Cache JS build output
+  #       # when in master repo: all commits to main branch and all additional tags
+  #       if: github.ref == 'refs/heads/main' || (github.ref != 'refs/heads/main' && startsWith( github.ref, 'refs/tags/') )
+  #       uses: actions/cache/save@v4
+  #       with:
+  #         path: |
+  #           out/morphir/${{matrix.scala}}/**/js/
+  #         key: ${{ runner.os }}-mill-js-${{matrix.java}}-${{ matrix.scala }}-${{ github.sha}}-${{ hashFiles('out') }}
 
   test-jvm:
     runs-on: ubuntu-latest
@@ -125,6 +125,8 @@ jobs:
             out/morphir/${{matrix.scala}}/**/jvm/
             out/morphir/build/
           key: ${{ runner.os }}-mill-jvm-${{matrix.java}}-${{ matrix.scala }}-${{ github.sha }}-${{ hashFiles('out') }}
+
+      - 
 
   # test-native:
   #   runs-on: ubuntu-latest
@@ -191,15 +193,15 @@ jobs:
       SonatypeUrl: 'https://finos.sonatype.app/platform/'
       SonatypeAppId: morphir-scala
       SonatypeStage: build
-      SonatypeScanTarget: '/home/runner/'
+      SonatypeScanTarget: '${{ CACHE_BASE }}'
       ExcludeDirectory: " -X "
 
       # ExcludeDirectory: " -X -D dirExcludes='**/website/, **/docs/, **/.*'"
 
     steps:
-      - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
+      # - uses: actions/checkout@v4
+      #   with:
+      #     fetch-depth: 0
 
       - uses: actions/setup-java@v4
         with:
@@ -209,41 +211,41 @@ jobs:
       - name: Cache scala dependencies
         uses: coursier/cache-action@v6
 
-      - name: Install libuv
-        run: sudo apt-get update && sudo apt-get install -y libuv1-dev
+      # - name: Install libuv
+      #   run: sudo apt-get update && sudo apt-get install -y libuv1-dev
 
-      - name: Restore Scala 2.13 JVM Build Output From Cache
-        uses: actions/cache/restore@v4
-        with:
-          path: |
-            out/morphir/2.13.13/**/jvm/
-            out/morphir/build/
-          key: ${{ runner.os }}-mill-jvm-11-2.13.13-${{ github.sha }}-${{ hashFiles('out') }}
-          restore-keys: ${{ runner.os }}-mill-jvm-11-2.13.13-${{ github.sha }}-
+      # - name: Restore Scala 2.13 JVM Build Output From Cache
+      #   uses: actions/cache/restore@v4
+      #   with:
+      #     path: |
+      #       out/morphir/2.13.13/**/jvm/
+      #       out/morphir/build/
+      #     key: ${{ runner.os }}-mill-jvm-11-2.13.13-${{ github.sha }}-${{ hashFiles('out') }}
+      #     restore-keys: ${{ runner.os }}-mill-jvm-11-2.13.13-${{ github.sha }}-
 
-      - name: Restore Scala 3.3 JVM Build Output From Cache
-        uses: actions/cache/restore@v4
-        with:
-          path: |
-            out/morphir/3.3.3/**/jvm/
-          key: ${{ runner.os }}-mill-jvm-11-3.3.3-${{ github.sha }}-${{ hashFiles('out') }}
-          restore-keys: ${{ runner.os }}-mill-jvm-11-3.3.3-${{ github.sha }}-
+      # - name: Restore Scala 3.3 JVM Build Output From Cache
+      #   uses: actions/cache/restore@v4
+      #   with:
+      #     path: |
+      #       out/morphir/3.3.3/**/jvm/
+      #     key: ${{ runner.os }}-mill-jvm-11-3.3.3-${{ github.sha }}-${{ hashFiles('out') }}
+      #     restore-keys: ${{ runner.os }}-mill-jvm-11-3.3.3-${{ github.sha }}-
 
-      - name: Restore Scala 2.13 JS Build Output From Cache
-        uses: actions/cache/restore@v4
-        with:
-          path: |
-            out/morphir/2.13.13/**/js/
-          key: ${{ runner.os }}-mill-js-11-2.13.13-${{ github.sha }}-${{ hashFiles('out') }}
-          restore-keys: ${{ runner.os }}-mill-js-11-2.13.13-${{ github.sha }}-
+      # - name: Restore Scala 2.13 JS Build Output From Cache
+      #   uses: actions/cache/restore@v4
+      #   with:
+      #     path: |
+      #       out/morphir/2.13.13/**/js/
+      #     key: ${{ runner.os }}-mill-js-11-2.13.13-${{ github.sha }}-${{ hashFiles('out') }}
+      #     restore-keys: ${{ runner.os }}-mill-js-11-2.13.13-${{ github.sha }}-
 
-      - name: Restore Scala 3.3 JS Build Output From Cache
-        uses: actions/cache/restore@v4
-        with:
-          path: |
-            out/morphir/3.3.3/**/js/
-          key: ${{ runner.os }}-mill-js-11-3.3.3-${{ github.sha }}-${{ hashFiles('out') }}
-          restore-keys: ${{ runner.os }}-mill-js-11-3.3.3-${{ github.sha }}-
+      # - name: Restore Scala 3.3 JS Build Output From Cache
+      #   uses: actions/cache/restore@v4
+      #   with:
+      #     path: |
+      #       out/morphir/3.3.3/**/js/
+      #     key: ${{ runner.os }}-mill-js-11-3.3.3-${{ github.sha }}-${{ hashFiles('out') }}
+      #     restore-keys: ${{ runner.os }}-mill-js-11-3.3.3-${{ github.sha }}-
 
       # - name: Restore Scala 2.13 Native Build Output From Cache
       #   uses: actions/cache/restore@v4
@@ -263,18 +265,18 @@ jobs:
 
       # - run: ./mill -i -j 0 io.kipp.mill.ci.release.ReleaseModule/publishAll
       
-      - run: ./mill -i -j 0 __.publishArtifacts 
-      - run: |
-          # Find all *.pom files and rename them to pom.xml
-          find . -type f -name "*.pom" | while read -r file; do
-            # Extract the directory of the current file
-            dir=$(dirname "$file")
-            new_name="${dir}/pom.xml"
-            # Rename the file
-            cp "$file" "$new_name"
-            echo "\n\nCopied: $file -> $new_name"
-            cat $new_name
-          done
+      # - run: ./mill -i -j 0 __.publishArtifacts 
+      # - run: |
+      #     # Find all *.pom files and rename them to pom.xml
+      #     find . -type f -name "*.pom" | while read -r file; do
+      #       # Extract the directory of the current file
+      #       dir=$(dirname "$file")
+      #       new_name="${dir}/pom.xml"
+      #       # Rename the file
+      #       cp "$file" "$new_name"
+      #       echo "\n\nCopied: $file -> $new_name"
+      #       cat $new_name
+      #     done
 
       - name: Sonatype Lifecycle SCA Scan
         uses: sonatype-nexus-community/iq-github-action@master
@@ -286,18 +288,18 @@ jobs:
           stage: ${{ env.SonatypeStage }}
           target: ${{ env.SonatypeScanTarget }} ${{ env.ExcludeDirectory }}
 
-      - name: Upload OUT dir
-        if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: OUT Directory
-          path: /home/runner/work/morphir-scala/morphir-scala/out/
+      # - name: Upload OUT dir
+      #   if: always()
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: OUT Directory
+      #     path: /home/runner/work/morphir-scala/morphir-scala/out/
         
 
   ci:
     runs-on: ubuntu-latest
     # needs: [lint, test-js, test-jvm, test-native]
-    needs: [lint, test-js, test-jvm]
+    needs: [test-jvm]
     steps:
       - name: Aggregate of lint, and all tests
         run: echo "ci passed"
