Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -25,151 +25,151 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
-  lint:
-    runs-on: ubuntu-latest
-    timeout-minutes: 30
-    steps:
-      - name: Checkout current branch
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      - name: Setup Scala and Java
-        uses: actions/setup-java@v4
-        with:
-          distribution: "temurin"
-          java-version: "17"
-      - name: Cache scala dependencies
-        uses: coursier/cache-action@v6
-      - name: Setup proto and moon toolchains
-        uses: moonrepo/setup-toolchain@v0.3.1
-        with:
-          auto-install: true
+  # lint:
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 30
+  #   steps:
+  #     - name: Checkout current branch
+  #       uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 0
+  #     - name: Setup Scala and Java
+  #       uses: actions/setup-java@v4
+  #       with:
+  #         distribution: "temurin"
+  #         java-version: "17"
+  #     - name: Cache scala dependencies
+  #       uses: coursier/cache-action@v6
+  #     - name: Setup proto and moon toolchains
+  #       uses: moonrepo/setup-toolchain@v0.3.1
+  #       with:
+  #         auto-install: true
             
-      - name: Install tooling
-        run: |
-          ./build.sh install
-      - name: Lint code
-        run: ./build.sh lint
+  #     - name: Install tooling
+  #       run: |
+  #         ./build.sh install
+  #     - name: Lint code
+  #       run: ./build.sh lint
 
-  test-js:
-    runs-on: ubuntu-latest
-    timeout-minutes: 30
-    strategy:
-      fail-fast: false
-      matrix:
-        java: ["11"] # Note there is no need ro actually run this for multiple JVM versions for JS
-        scala: ["2.13.14", "3.3.3"]
-    steps:
-      - name: Checkout current branch
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      - name: Setup Scala and Java
-        uses: actions/setup-java@v4
-        with:
-          distribution: "temurin"
-          java-version: ${{ matrix.java }}
-      - name: Cache scala dependencies
-        uses: coursier/cache-action@v6
+  # test-js:
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 30
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       java: ["11"] # Note there is no need ro actually run this for multiple JVM versions for JS
+  #       scala: ["2.13.14", "3.3.3"]
+  #   steps:
+  #     - name: Checkout current branch
+  #       uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 0
+  #     - name: Setup Scala and Java
+  #       uses: actions/setup-java@v4
+  #       with:
+  #         distribution: "temurin"
+  #         java-version: ${{ matrix.java }}
+  #     - name: Cache scala dependencies
+  #       uses: coursier/cache-action@v6
 
-      - name: Run JS tests
-        run: |
-          ./mill -i -k -j 0 "morphir[${{matrix.scala}}].__.js.__.compile" + "morphir[${{matrix.scala}}].__.js.publishArtifacts" + "morphir[${{matrix.scala}}].__.js.__.test"
+  #     - name: Run JS tests
+  #       run: |
+  #         ./mill -i -k -j 0 "morphir[${{matrix.scala}}].__.js.__.compile" + "morphir[${{matrix.scala}}].__.js.publishArtifacts" + "morphir[${{matrix.scala}}].__.js.__.test"
 
-      - name: Cache JS build output
-        # when in master repo: all commits to main branch and all additional tags
-        if: github.ref == 'refs/heads/main' || (github.ref != 'refs/heads/main' && startsWith( github.ref, 'refs/tags/') )
-        uses: actions/cache/save@v4
-        with:
-          path: |
-            out/morphir/${{matrix.scala}}/**/js/
-          key: ${{ runner.os }}-mill-js-${{matrix.java}}-${{ matrix.scala }}-${{ github.sha}}-${{ hashFiles('out') }}
+  #     - name: Cache JS build output
+  #       # when in master repo: all commits to main branch and all additional tags
+  #       if: github.ref == 'refs/heads/main' || (github.ref != 'refs/heads/main' && startsWith( github.ref, 'refs/tags/') )
+  #       uses: actions/cache/save@v4
+  #       with:
+  #         path: |
+  #           out/morphir/${{matrix.scala}}/**/js/
+  #         key: ${{ runner.os }}-mill-js-${{matrix.java}}-${{ matrix.scala }}-${{ github.sha}}-${{ hashFiles('out') }}
 
-  test-jvm:
-    runs-on: ubuntu-latest
-    timeout-minutes: 30
-    strategy:
-      fail-fast: false
-      matrix:
-        java: ["11", "17"]
-        scala: ["2.13.14", "3.3.3"]
-    steps:
-      - name: Checkout current branch
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      - name: Setup Scala and Java
-        uses: actions/setup-java@v4
-        with:
-          distribution: "temurin"
-          java-version: ${{ matrix.java }}
-      - name: Cache scala dependencies
-        uses: coursier/cache-action@v6
+  # test-jvm:
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 30
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       java: ["11", "17"]
+  #       scala: ["2.13.14", "3.3.3"]
+  #   steps:
+  #     - name: Checkout current branch
+  #       uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 0
+  #     - name: Setup Scala and Java
+  #       uses: actions/setup-java@v4
+  #       with:
+  #         distribution: "temurin"
+  #         java-version: ${{ matrix.java }}
+  #     - name: Cache scala dependencies
+  #       uses: coursier/cache-action@v6
 
-      - name: Setup proto and moon toolchains
-        uses: moonrepo/setup-toolchain@v0.3.1
-        with:
-          auto-install: true
+  #     - name: Setup proto and moon toolchains
+  #       uses: moonrepo/setup-toolchain@v0.3.1
+  #       with:
+  #         auto-install: true
             
-      - name: Install tooling
-        run: |
-          ./build.sh install
-      - name: Make Morphir IR
-        run: |
-          ./build.sh run :morphir-elm-build
-      - name: Run JVM tests
-        run: |
-          ./build.sh --scala-version ${{matrix.scala}} test-jvm
+  #     - name: Install tooling
+  #       run: |
+  #         ./build.sh install
+  #     - name: Make Morphir IR
+  #       run: |
+  #         ./build.sh run :morphir-elm-build
+  #     - name: Run JVM tests
+  #       run: |
+  #         ./build.sh --scala-version ${{matrix.scala}} test-jvm
 
-      - name: Cache JVM build output
-        # when in master repo: all commits to main branch and all additional tags
-        if: github.ref == 'refs/heads/main' || (github.ref != 'refs/heads/main' && startsWith( github.ref, 'refs/tags/') )
-        uses: actions/cache/save@v4
-        with:
-          path: |
-            out/morphir/${{matrix.scala}}/**/jvm/
-            out/morphir/build/
-          key: ${{ runner.os }}-mill-jvm-${{matrix.java}}-${{ matrix.scala }}-${{ github.sha }}-${{ hashFiles('out') }}
+  #     - name: Cache JVM build output
+  #       # when in master repo: all commits to main branch and all additional tags
+  #       if: github.ref == 'refs/heads/main' || (github.ref != 'refs/heads/main' && startsWith( github.ref, 'refs/tags/') )
+  #       uses: actions/cache/save@v4
+  #       with:
+  #         path: |
+  #           out/morphir/${{matrix.scala}}/**/jvm/
+  #           out/morphir/build/
+  #         key: ${{ runner.os }}-mill-jvm-${{matrix.java}}-${{ matrix.scala }}-${{ github.sha }}-${{ hashFiles('out') }}
 
-  test-native:
-    runs-on: ubuntu-latest
-    timeout-minutes: 30
-    strategy:
-      fail-fast: false
-      matrix:
-        java: ["11"] # Note there is no need ro actually run this for multiple JVM versions for native
-        scala: ["2.13.14", "3.3.3"]
-    steps:
-      - name: Checkout current branch
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      - name: Install libuv
-        run: sudo apt-get update && sudo apt-get install -y libuv1-dev
+  # test-native:
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 30
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       java: ["11"] # Note there is no need ro actually run this for multiple JVM versions for native
+  #       scala: ["2.13.14", "3.3.3"]
+  #   steps:
+  #     - name: Checkout current branch
+  #       uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 0
+  #     - name: Install libuv
+  #       run: sudo apt-get update && sudo apt-get install -y libuv1-dev
 
-      - name: Set up Clang
-        uses: egor-tensin/setup-clang@v1
-        with:
-          version: latest
-          platform: x64
-      - name: Setup Scala and Java
-        uses: actions/setup-java@v4
-        with:
-          distribution: "temurin"
-          java-version: ${{ matrix.java }}
+  #     - name: Set up Clang
+  #       uses: egor-tensin/setup-clang@v1
+  #       with:
+  #         version: latest
+  #         platform: x64
+  #     - name: Setup Scala and Java
+  #       uses: actions/setup-java@v4
+  #       with:
+  #         distribution: "temurin"
+  #         java-version: ${{ matrix.java }}
 
-      - name: Run Native tests
-        run: |
-          ./mill -i -k -j 0 "morphir[${{matrix.scala}}].__.native.__.compile" + "morphir[${{matrix.scala}}].__.native.publishArtifacts" + "morphir[${{matrix.scala}}].__.native.__.test"
+  #     - name: Run Native tests
+  #       run: |
+  #         ./mill -i -k -j 0 "morphir[${{matrix.scala}}].__.native.__.compile" + "morphir[${{matrix.scala}}].__.native.publishArtifacts" + "morphir[${{matrix.scala}}].__.native.__.test"
 
-      - name: Cache Native build output
-        # when in master repo: all commits to main branch and all additional tags
-        if: github.ref == 'refs/heads/main' || (github.ref != 'refs/heads/main' && startsWith( github.ref, 'refs/tags/') )
-        uses: actions/cache/save@v4
-        with:
-          path: |
-            out/morphir/${{matrix.scala}}/**/native/
-          key: ${{ runner.os }}-mill-native-${{matrix.java}}-${{ matrix.scala }}-${{ github.sha }}-${{ hashFiles('out') }}
+  #     - name: Cache Native build output
+  #       # when in master repo: all commits to main branch and all additional tags
+  #       if: github.ref == 'refs/heads/main' || (github.ref != 'refs/heads/main' && startsWith( github.ref, 'refs/tags/') )
+  #       uses: actions/cache/save@v4
+  #       with:
+  #         path: |
+  #           out/morphir/${{matrix.scala}}/**/native/
+  #         key: ${{ runner.os }}-mill-native-${{matrix.java}}-${{ matrix.scala }}-${{ github.sha }}-${{ hashFiles('out') }}
 
   ############### SONATYPE SCAN ###############
   sonatype-scan:
@@ -213,7 +213,7 @@ jobs:
       if: always()
       run: |
         mkdir reports/
-        iqCredentials=${{ secrets.SONATYPE_USER }}:${{ secrets.SONATYPE_PASSWORD }}
+        iqCredentials="${{ secrets.SONATYPE_USER }}:${{ secrets.SONATYPE_PASSWORD }}"
         echo 'Get internal app ID for public ID: '$SonatypeAppId
         res=$(curl -u $iqCredentials --location $SonatypeUrl'api/v2/applications?publicId='$SonatypeAppId)
         IFS='"' read -a array <<< "$res"
@@ -222,6 +222,7 @@ jobs:
         curl -u $iqCredentials --location $SonatypeUrl'api/v2/spdx/'$internalID'/stages/'$SonatypeStage -H 'Accept: application/xml' > reports/$SonatypeAppId.spdx.json
         echo 'Sonatype SBOM (SPDX): '
         cat reports/$SonatypeAppId.spdx.json
+        
     - name: Upload Sonatype SBOM (SPDX)
       if: always()
       uses: actions/upload-artifact@v4
