Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -4,7 +4,7 @@ env:
   JDK_JAVA_OPTIONS: -XX:+PrintCommandLineFlags -Xss10M # JDK_JAVA_OPTIONS is _the_ env. variable to use for modern Java
   JVM_OPTS: -XX:+PrintCommandLineFlags -Xss10M # for Java 8 only (sadly, it is not modern enough for JDK_JAVA_OPTIONS)
   SonatypeUrl: 'https://finos.sonatype.app/platform/'
-  SonatypeAppId: morphir-scala
+  SonatypeAppId: morphir-test
   SonatypeStage: 'build' 
   SonatypeScanTarget: 'depCache/coursier/' # depCache/coursier/v1/https/repo1.maven.org/maven2/
   ExcludeDirectory: " -D fileExcludes='*.class' "
@@ -26,65 +26,65 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
-  lint:
-    runs-on: ubuntu-latest
-    timeout-minutes: 30
-    steps:
-      - name: Checkout current branch
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      - name: Setup Scala and Java
-        uses: actions/setup-java@v4
-        with:
-          distribution: "temurin"
-          java-version: "17"
-      - name: Cache scala dependencies
-        uses: coursier/cache-action@v6
-      - name: Setup proto and moon toolchains
-        uses: moonrepo/setup-toolchain@v0.3.1
-        with:
-          auto-install: true
+  # lint:
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 30
+  #   steps:
+  #     - name: Checkout current branch
+  #       uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 0
+  #     - name: Setup Scala and Java
+  #       uses: actions/setup-java@v4
+  #       with:
+  #         distribution: "temurin"
+  #         java-version: "17"
+  #     - name: Cache scala dependencies
+  #       uses: coursier/cache-action@v6
+  #     - name: Setup proto and moon toolchains
+  #       uses: moonrepo/setup-toolchain@v0.3.1
+  #       with:
+  #         auto-install: true
             
-      - name: Install tooling
-        run: |
-          ./build.sh install
-      - name: Lint code
-        run: ./build.sh lint
+  #     - name: Install tooling
+  #       run: |
+  #         ./build.sh install
+  #     - name: Lint code
+  #       run: ./build.sh lint
 
-  test-js:
-    runs-on: ubuntu-latest
-    timeout-minutes: 30
-    strategy:
-      fail-fast: false
-      matrix:
-        java: ["11"] # Note there is no need ro actually run this for multiple JVM versions for JS
-        scala: ["2.13.13", "3.3.3"]
-    steps:
-      - name: Checkout current branch
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      - name: Setup Scala and Java
-        uses: actions/setup-java@v4
-        with:
-          distribution: "temurin"
-          java-version: ${{ matrix.java }}
-      - name: Cache scala dependencies
-        uses: coursier/cache-action@v6
+  # test-js:
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 30
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       java: ["11"] # Note there is no need ro actually run this for multiple JVM versions for JS
+  #       scala: ["2.13.13", "3.3.3"]
+  #   steps:
+  #     - name: Checkout current branch
+  #       uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 0
+  #     - name: Setup Scala and Java
+  #       uses: actions/setup-java@v4
+  #       with:
+  #         distribution: "temurin"
+  #         java-version: ${{ matrix.java }}
+  #     - name: Cache scala dependencies
+  #       uses: coursier/cache-action@v6
 
-      - name: Run JS tests
-        run: |
-          ./mill -i -k -j 0 "morphir[${{matrix.scala}}].__.js.__.compile" + "morphir[${{matrix.scala}}].__.js.publishArtifacts" + "morphir[${{matrix.scala}}].__.js.__.test"
+  #     - name: Run JS tests
+  #       run: |
+  #         ./mill -i -k -j 0 "morphir[${{matrix.scala}}].__.js.__.compile" + "morphir[${{matrix.scala}}].__.js.publishArtifacts" + "morphir[${{matrix.scala}}].__.js.__.test"
 
-      - name: Cache JS build output
-        # when in master repo: all commits to main branch and all additional tags
-        if: github.ref == 'refs/heads/main' || (github.ref != 'refs/heads/main' && startsWith( github.ref, 'refs/tags/') )
-        uses: actions/cache/save@v4
-        with:
-          path: |
-            out/morphir/${{matrix.scala}}/**/js/
-          key: ${{ runner.os }}-mill-js-${{matrix.java}}-${{ matrix.scala }}-${{ github.sha}}-${{ hashFiles('out') }}
+  #     - name: Cache JS build output
+  #       # when in master repo: all commits to main branch and all additional tags
+  #       if: github.ref == 'refs/heads/main' || (github.ref != 'refs/heads/main' && startsWith( github.ref, 'refs/tags/') )
+  #       uses: actions/cache/save@v4
+  #       with:
+  #         path: |
+  #           out/morphir/${{matrix.scala}}/**/js/
+  #         key: ${{ runner.os }}-mill-js-${{matrix.java}}-${{ matrix.scala }}-${{ github.sha}}-${{ hashFiles('out') }}
 
   test-jvm:
     runs-on: ubuntu-latest
@@ -137,45 +137,45 @@ jobs:
             out/morphir/build/
           key: ${{ runner.os }}-mill-jvm-${{matrix.java}}-${{ matrix.scala }}-${{ github.sha }}-${{ hashFiles('out') }}
           
-  test-native:
-    runs-on: ubuntu-latest
-    timeout-minutes: 30
-    strategy:
-      fail-fast: false
-      matrix:
-        java: ["11"] # Note there is no need ro actually run this for multiple JVM versions for native
-        scala: ["2.13.13", "3.3.3"]
-    steps:
-      - name: Checkout current branch
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      - name: Install libuv
-        run: sudo apt-get update && sudo apt-get install -y libuv1-dev
+  # test-native:
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 30
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       java: ["11"] # Note there is no need ro actually run this for multiple JVM versions for native
+  #       scala: ["2.13.13", "3.3.3"]
+  #   steps:
+  #     - name: Checkout current branch
+  #       uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 0
+  #     - name: Install libuv
+  #       run: sudo apt-get update && sudo apt-get install -y libuv1-dev
 
-      - name: Set up Clang
-        uses: egor-tensin/setup-clang@v1
-        with:
-          version: latest
-          platform: x64
-      - name: Setup Scala and Java
-        uses: actions/setup-java@v4
-        with:
-          distribution: "temurin"
-          java-version: ${{ matrix.java }}
+  #     - name: Set up Clang
+  #       uses: egor-tensin/setup-clang@v1
+  #       with:
+  #         version: latest
+  #         platform: x64
+  #     - name: Setup Scala and Java
+  #       uses: actions/setup-java@v4
+  #       with:
+  #         distribution: "temurin"
+  #         java-version: ${{ matrix.java }}
 
-      - name: Run Native tests
-        run: |
-          ./mill -i -k -j 0 "morphir[${{matrix.scala}}].__.native.__.compile" + "morphir[${{matrix.scala}}].__.native.publishArtifacts" + "morphir[${{matrix.scala}}].__.native.__.test"
+  #     - name: Run Native tests
+  #       run: |
+  #         ./mill -i -k -j 0 "morphir[${{matrix.scala}}].__.native.__.compile" + "morphir[${{matrix.scala}}].__.native.publishArtifacts" + "morphir[${{matrix.scala}}].__.native.__.test"
 
-      - name: Cache Native build output
-        # when in master repo: all commits to main branch and all additional tags
-        if: github.ref == 'refs/heads/main' || (github.ref != 'refs/heads/main' && startsWith( github.ref, 'refs/tags/') )
-        uses: actions/cache/save@v4
-        with:
-          path: |
-            out/morphir/${{matrix.scala}}/**/native/
-          key: ${{ runner.os }}-mill-native-${{matrix.java}}-${{ matrix.scala }}-${{ github.sha }}-${{ hashFiles('out') }}
+  #     - name: Cache Native build output
+  #       # when in master repo: all commits to main branch and all additional tags
+  #       if: github.ref == 'refs/heads/main' || (github.ref != 'refs/heads/main' && startsWith( github.ref, 'refs/tags/') )
+  #       uses: actions/cache/save@v4
+  #       with:
+  #         path: |
+  #           out/morphir/${{matrix.scala}}/**/native/
+  #         key: ${{ runner.os }}-mill-native-${{matrix.java}}-${{ matrix.scala }}-${{ github.sha }}-${{ hashFiles('out') }}
 
 
   ############### SONATYPE SCAN ###############
@@ -184,9 +184,13 @@ jobs:
     needs: [ci]
     runs-on: ubuntu-latest
     steps:
+    - name: Cache scala dependencies
+      uses: coursier/cache-action@v6
+        
     - name: Copy Cache for SCA Scan
       run: |
         mkdir depCache/
+        ls -al /home/runner/.cache/
         cp -r /home/runner/.cache/coursier/ depCache/
 
     - name: Save resolvedIvyDeps.json
@@ -337,7 +341,8 @@ jobs:
 
   ci:
     runs-on: ubuntu-latest
-    needs: [lint, test-js, test-jvm, test-native]
+    needs: [test-jvm]
+    # needs: [lint, test-js, test-jvm, test-native]
     steps:
       - name: Aggregate of lint, and all tests
         run: echo "ci passed"
