Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -61,116 +61,116 @@ jobs:
           stage: ${{ env.SonatypeStage }}
           target: ${{ env.SonatypeScanTarget }} ${{ env.ExcludeDirectory }}
 
-  test-js:
-    runs-on: ubuntu-latest
-    timeout-minutes: 30
-    strategy:
-      fail-fast: false
-      matrix:
-        java: ["11"] # Note there is no need ro actually run this for multiple JVM versions for JS
-        scala: ["2.13.13", "3.3.3"]
-    steps:
-      - name: Checkout current branch
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      - name: Setup Scala and Java
-        uses: actions/setup-java@v4
-        with:
-          distribution: "temurin"
-          java-version: ${{ matrix.java }}
-      - name: Cache scala dependencies
-        uses: coursier/cache-action@v6
+  # test-js:
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 30
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       java: ["11"] # Note there is no need ro actually run this for multiple JVM versions for JS
+  #       scala: ["2.13.13", "3.3.3"]
+  #   steps:
+  #     - name: Checkout current branch
+  #       uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 0
+  #     - name: Setup Scala and Java
+  #       uses: actions/setup-java@v4
+  #       with:
+  #         distribution: "temurin"
+  #         java-version: ${{ matrix.java }}
+  #     - name: Cache scala dependencies
+  #       uses: coursier/cache-action@v6
 
-      - name: Run JS tests
-        run: |
-          ./mill -i -k -j 0 "morphir[${{matrix.scala}}].__.js.__.compile" + "morphir[${{matrix.scala}}].__.js.publishArtifacts" + "morphir[${{matrix.scala}}].__.js.__.test"
+  #     - name: Run JS tests
+  #       run: |
+  #         ./mill -i -k -j 0 "morphir[${{matrix.scala}}].__.js.__.compile" + "morphir[${{matrix.scala}}].__.js.publishArtifacts" + "morphir[${{matrix.scala}}].__.js.__.test"
 
-      - name: Cache JS build output
-        # when in master repo: all commits to main branch and all additional tags
-        if: github.ref == 'refs/heads/main' || (github.ref != 'refs/heads/main' && startsWith( github.ref, 'refs/tags/') )
-        uses: actions/cache/save@v4
-        with:
-          path: |
-            out/morphir/${{matrix.scala}}/**/js/
-          key: ${{ runner.os }}-mill-js-${{matrix.java}}-${{ matrix.scala }}-${{ github.sha}}-${{ hashFiles('out') }}
+  #     - name: Cache JS build output
+  #       # when in master repo: all commits to main branch and all additional tags
+  #       if: github.ref == 'refs/heads/main' || (github.ref != 'refs/heads/main' && startsWith( github.ref, 'refs/tags/') )
+  #       uses: actions/cache/save@v4
+  #       with:
+  #         path: |
+  #           out/morphir/${{matrix.scala}}/**/js/
+  #         key: ${{ runner.os }}-mill-js-${{matrix.java}}-${{ matrix.scala }}-${{ github.sha}}-${{ hashFiles('out') }}
 
-  test-jvm:
-    runs-on: ubuntu-latest
-    timeout-minutes: 30
-    strategy:
-      fail-fast: false
-      matrix:
-        java: ["11", "17"]
-        scala: ["2.13.13", "3.3.3"]
-    steps:
-      - name: Checkout current branch
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      - name: Setup Scala and Java
-        uses: actions/setup-java@v4
-        with:
-          distribution: "temurin"
-          java-version: ${{ matrix.java }}
-      - name: Cache scala dependencies
-        uses: coursier/cache-action@v6
+  # test-jvm:
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 30
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       java: ["11", "17"]
+  #       scala: ["2.13.13", "3.3.3"]
+  #   steps:
+  #     - name: Checkout current branch
+  #       uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 0
+  #     - name: Setup Scala and Java
+  #       uses: actions/setup-java@v4
+  #       with:
+  #         distribution: "temurin"
+  #         java-version: ${{ matrix.java }}
+  #     - name: Cache scala dependencies
+  #       uses: coursier/cache-action@v6
 
-      - name: Setup proto and moon toolchains
-        uses: moonrepo/setup-toolchain@v0.3.1
-        with:
-          auto-install: true
+  #     - name: Setup proto and moon toolchains
+  #       uses: moonrepo/setup-toolchain@v0.3.1
+  #       with:
+  #         auto-install: true
             
-      - name: Install tooling
-        run: |
-          ./build.sh install
-      - name: Make Morphir IR
-        run: |
-          ./build.sh run :morphir-elm-build
-      - name: Run JVM tests
-        run: |
-          ./build.sh --scala-version ${{matrix.scala}} test-jvm
+  #     - name: Install tooling
+  #       run: |
+  #         ./build.sh install
+  #     - name: Make Morphir IR
+  #       run: |
+  #         ./build.sh run :morphir-elm-build
+  #     - name: Run JVM tests
+  #       run: |
+  #         ./build.sh --scala-version ${{matrix.scala}} test-jvm
 
-      - name: Cache JVM build output
-        # when in master repo: all commits to main branch and all additional tags
-        if: github.ref == 'refs/heads/main' || (github.ref != 'refs/heads/main' && startsWith( github.ref, 'refs/tags/') )
-        uses: actions/cache/save@v4
-        with:
-          path: |
-            out/morphir/${{matrix.scala}}/**/jvm/
-            out/morphir/build/
-          key: ${{ runner.os }}-mill-jvm-${{matrix.java}}-${{ matrix.scala }}-${{ github.sha }}-${{ hashFiles('out') }}
+  #     - name: Cache JVM build output
+  #       # when in master repo: all commits to main branch and all additional tags
+  #       if: github.ref == 'refs/heads/main' || (github.ref != 'refs/heads/main' && startsWith( github.ref, 'refs/tags/') )
+  #       uses: actions/cache/save@v4
+  #       with:
+  #         path: |
+  #           out/morphir/${{matrix.scala}}/**/jvm/
+  #           out/morphir/build/
+  #         key: ${{ runner.os }}-mill-jvm-${{matrix.java}}-${{ matrix.scala }}-${{ github.sha }}-${{ hashFiles('out') }}
 
-  test-native:
-    runs-on: ubuntu-latest
-    timeout-minutes: 30
-    strategy:
-      fail-fast: false
-      matrix:
-        java: ["11"] # Note there is no need ro actually run this for multiple JVM versions for native
-        scala: ["2.13.13", "3.3.3"]
-    steps:
-      - name: Checkout current branch
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      - name: Install libuv
-        run: sudo apt-get update && sudo apt-get install -y libuv1-dev
+  # test-native:
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 30
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       java: ["11"] # Note there is no need ro actually run this for multiple JVM versions for native
+  #       scala: ["2.13.13", "3.3.3"]
+  #   steps:
+  #     - name: Checkout current branch
+  #       uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 0
+  #     - name: Install libuv
+  #       run: sudo apt-get update && sudo apt-get install -y libuv1-dev
 
-      - name: Set up Clang
-        uses: egor-tensin/setup-clang@v1
-        with:
-          version: latest
-          platform: x64
-      - name: Setup Scala and Java
-        uses: actions/setup-java@v4
-        with:
-          distribution: "temurin"
-          java-version: ${{ matrix.java }}
+  #     - name: Set up Clang
+  #       uses: egor-tensin/setup-clang@v1
+  #       with:
+  #         version: latest
+  #         platform: x64
+  #     - name: Setup Scala and Java
+  #       uses: actions/setup-java@v4
+  #       with:
+  #         distribution: "temurin"
+  #         java-version: ${{ matrix.java }}
 
-      - name: Run Native tests
-        run: |
-          ./mill -i -k -j 0 "morphir[${{matrix.scala}}].__.native.__.compile" + "morphir[${{matrix.scala}}].__.native.publishArtifacts" + "morphir[${{matrix.scala}}].__.native.__.test"
+  #     - name: Run Native tests
+  #       run: |
+  #         ./mill -i -k -j 0 "morphir[${{matrix.scala}}].__.native.__.compile" + "morphir[${{matrix.scala}}].__.native.publishArtifacts" + "morphir[${{matrix.scala}}].__.native.__.test"
 
       - name: Cache Native build output
         # when in master repo: all commits to main branch and all additional tags
@@ -182,97 +182,102 @@ jobs:
           key: ${{ runner.os }}-mill-native-${{matrix.java}}-${{ matrix.scala }}-${{ github.sha }}-${{ hashFiles('out') }}
 
 
-  # publish-sonatype:
-  #   # when in master repo: all commits to main branch and all additional tags
-  #   if: github.repository == 'finos/morphir-scala' && ( github.ref == 'refs/heads/main' || (github.ref != 'refs/heads/main' && startsWith( github.ref, 'refs/tags/') ) )
-  #   needs: [ci]
+  publish-sonatype:
+    # when in master repo: all commits to main branch and all additional tags
+    # if: github.repository == 'finos/morphir-scala' && ( github.ref == 'refs/heads/main' || (github.ref != 'refs/heads/main' && startsWith( github.ref, 'refs/tags/') ) )
+    needs: [ci]
 
-  #   runs-on: ubuntu-latest
+    runs-on: ubuntu-latest
 
-  #   # only run one publish job for the same sha at the same time
-  #   # e.g. when a main-branch push is also tagged
-  #   concurrency: publish-sonatype-${{ github.sha }}
+    # only run one publish job for the same sha at the same time
+    # e.g. when a main-branch push is also tagged
+    concurrency: publish-sonatype-${{ github.sha }}
 
-  #   env:
-  #     PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
-  #     PGP_SECRET: ${{ secrets.PGP_SECRET_BASE64 }}
-  #     SONATYPE_PASSWORD: ${{ secrets.MAVEN_DEPLOY_PASSWORD }}
-  #     SONATYPE_USERNAME: ${{ secrets.MAVEN_DEPLOY_USERNAME }}
-  #     PUBLISH_AS_SNAPSHOT: true
-  #     LANG: "en_US.UTF-8"
-  #     LC_MESSAGES: "en_US.UTF-8"
-  #     LC_ALL: "en_US.UTF-8"
+    env:
+      PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
+      PGP_SECRET: ${{ secrets.PGP_SECRET_BASE64 }}
+      SONATYPE_PASSWORD: ${{ secrets.MAVEN_DEPLOY_PASSWORD }}
+      SONATYPE_USERNAME: ${{ secrets.MAVEN_DEPLOY_USERNAME }}
+      PUBLISH_AS_SNAPSHOT: true
+      LANG: "en_US.UTF-8"
+      LC_MESSAGES: "en_US.UTF-8"
+      LC_ALL: "en_US.UTF-8"
 
-  #   steps:
-  #     - uses: actions/checkout@v4
-  #       with:
-  #         fetch-depth: 0
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
 
-  #     - uses: actions/setup-java@v4
-  #       with:
-  #         java-version: "11"
-  #         distribution: temurin
+      - uses: actions/setup-java@v4
+        with:
+          java-version: "11"
+          distribution: temurin
 
-  #     - name: Cache scala dependencies
-  #       uses: coursier/cache-action@v6
+      - name: Cache scala dependencies
+        uses: coursier/cache-action@v6
 
-  #     - name: Install libuv
-  #       run: sudo apt-get update && sudo apt-get install -y libuv1-dev
+      - name: Install libuv
+        run: sudo apt-get update && sudo apt-get install -y libuv1-dev
 
-  #     - name: Restore Scala 2.13 JVM Build Output From Cache
-  #       uses: actions/cache/restore@v4
-  #       with:
-  #         path: |
-  #           out/morphir/2.13.13/**/jvm/
-  #           out/morphir/build/
-  #         key: ${{ runner.os }}-mill-jvm-11-2.13.13-${{ github.sha }}-${{ hashFiles('out') }}
-  #         restore-keys: ${{ runner.os }}-mill-jvm-11-2.13.13-${{ github.sha }}-
+      - name: Restore Scala 2.13 JVM Build Output From Cache
+        uses: actions/cache/restore@v4
+        with:
+          path: |
+            out/morphir/2.13.13/**/jvm/
+            out/morphir/build/
+          key: ${{ runner.os }}-mill-jvm-11-2.13.13-${{ github.sha }}-${{ hashFiles('out') }}
+          restore-keys: ${{ runner.os }}-mill-jvm-11-2.13.13-${{ github.sha }}-
 
-  #     - name: Restore Scala 3.3 JVM Build Output From Cache
-  #       uses: actions/cache/restore@v4
-  #       with:
-  #         path: |
-  #           out/morphir/3.3.3/**/jvm/
-  #         key: ${{ runner.os }}-mill-jvm-11-3.3.3-${{ github.sha }}-${{ hashFiles('out') }}
-  #         restore-keys: ${{ runner.os }}-mill-jvm-11-3.3.3-${{ github.sha }}-
+      - name: Restore Scala 3.3 JVM Build Output From Cache
+        uses: actions/cache/restore@v4
+        with:
+          path: |
+            out/morphir/3.3.3/**/jvm/
+          key: ${{ runner.os }}-mill-jvm-11-3.3.3-${{ github.sha }}-${{ hashFiles('out') }}
+          restore-keys: ${{ runner.os }}-mill-jvm-11-3.3.3-${{ github.sha }}-
 
-  #     - name: Restore Scala 2.13 JS Build Output From Cache
-  #       uses: actions/cache/restore@v4
-  #       with:
-  #         path: |
-  #           out/morphir/2.13.13/**/js/
-  #         key: ${{ runner.os }}-mill-js-11-2.13.13-${{ github.sha }}-${{ hashFiles('out') }}
-  #         restore-keys: ${{ runner.os }}-mill-js-11-2.13.13-${{ github.sha }}-
+      - name: Restore Scala 2.13 JS Build Output From Cache
+        uses: actions/cache/restore@v4
+        with:
+          path: |
+            out/morphir/2.13.13/**/js/
+          key: ${{ runner.os }}-mill-js-11-2.13.13-${{ github.sha }}-${{ hashFiles('out') }}
+          restore-keys: ${{ runner.os }}-mill-js-11-2.13.13-${{ github.sha }}-
 
-  #     - name: Restore Scala 3.3 JS Build Output From Cache
-  #       uses: actions/cache/restore@v4
-  #       with:
-  #         path: |
-  #           out/morphir/3.3.3/**/js/
-  #         key: ${{ runner.os }}-mill-js-11-3.3.3-${{ github.sha }}-${{ hashFiles('out') }}
-  #         restore-keys: ${{ runner.os }}-mill-js-11-3.3.3-${{ github.sha }}-
+      - name: Restore Scala 3.3 JS Build Output From Cache
+        uses: actions/cache/restore@v4
+        with:
+          path: |
+            out/morphir/3.3.3/**/js/
+          key: ${{ runner.os }}-mill-js-11-3.3.3-${{ github.sha }}-${{ hashFiles('out') }}
+          restore-keys: ${{ runner.os }}-mill-js-11-3.3.3-${{ github.sha }}-
 
-  #     - name: Restore Scala 2.13 Native Build Output From Cache
-  #       uses: actions/cache/restore@v4
-  #       with:
-  #         path: |
-  #           out/morphir/2.13.13/**/native/
-  #         key: ${{ runner.os }}-mill-native-11-2.13.13-${{ github.sha }}-${{ hashFiles('out') }}
-  #         restore-keys: ${{ runner.os }}-mill-native-11-2.13.13-${{ github.sha }}-
+      - name: Restore Scala 2.13 Native Build Output From Cache
+        uses: actions/cache/restore@v4
+        with:
+          path: |
+            out/morphir/2.13.13/**/native/
+          key: ${{ runner.os }}-mill-native-11-2.13.13-${{ github.sha }}-${{ hashFiles('out') }}
+          restore-keys: ${{ runner.os }}-mill-native-11-2.13.13-${{ github.sha }}-
 
-  #     - name: Restore Scala 3.3 Native Build Output From Cache
-  #       uses: actions/cache/restore@v4
-  #       with:
-  #         path: |
-  #           out/morphir/3.3.3/**/native/
-  #         key: ${{ runner.os }}-mill-native-11-3.3.3-${{ github.sha }}-${{ hashFiles('out') }}
-  #         restore-keys: ${{ runner.os }}-mill-native-11-3.3.3-${{ github.sha }}-
+      - name: Restore Scala 3.3 Native Build Output From Cache
+        uses: actions/cache/restore@v4
+        with:
+          path: |
+            out/morphir/3.3.3/**/native/
+          key: ${{ runner.os }}-mill-native-11-3.3.3-${{ github.sha }}-${{ hashFiles('out') }}
+          restore-keys: ${{ runner.os }}-mill-native-11-3.3.3-${{ github.sha }}-
 
-  #     - run: ./mill -i -j 0 io.kipp.mill.ci.release.ReleaseModule/publishAll
+      # - run: ./mill -i -j 0 io.kipp.mill.ci.release.ReleaseModule/publishAll
+      - run: ./mill -i -j 0 __.publishArtifacts 
+      - run: |
+          ls -R
+        
+      # LS and SCAN OUT DIRECTORY
 
-  # ci:
-  #   runs-on: ubuntu-latest
-  #   needs: [lint, test-js, test-jvm, test-native]
-  #   steps:
-  #     - name: Aggregate of lint, and all tests
-  #       run: echo "ci passed"
+  ci:
+    runs-on: ubuntu-latest
+    # needs: [lint, test-js, test-jvm, test-native]
+    steps:
+      - name: Aggregate of lint, and all tests
+        run: echo "ci passed"
