Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -51,105 +51,105 @@ jobs:
       - name: Lint code
         run: ./build.sh lint
 
-  test-js:
-    runs-on: ubuntu-latest
-    timeout-minutes: 30
-    strategy:
-      fail-fast: false
-      matrix:
-        java: ["11"] # Note there is no need ro actually run this for multiple JVM versions for JS
-        scala: ["3.3.3"]
-    steps:
-      - name: Checkout current branch
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
+  # test-js:
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 30
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       java: ["11"] # Note there is no need ro actually run this for multiple JVM versions for JS
+  #       scala: ["3.3.3"]
+  #   steps:
+  #     - name: Checkout current branch
+  #       uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 0
 
-      - name: Setup Node.js
-        uses: actions/setup-node@v4
-        with:
-          node-version-file: ".nvmrc"
+  #     - name: Setup Node.js
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version-file: ".nvmrc"
 
-      - name: Install morphir-elm
-        run: |
-          npm install -g morphir-elm
+  #     - name: Install morphir-elm
+  #       run: |
+  #         npm install -g morphir-elm
 
-      - name: Setup Scala and Java
-        uses: actions/setup-java@v4
-        with:
-          distribution: "temurin"
-          java-version: ${{ matrix.java }}
-      - name: Cache scala dependencies
-        uses: coursier/cache-action@v6
+  #     - name: Setup Scala and Java
+  #       uses: actions/setup-java@v4
+  #       with:
+  #         distribution: "temurin"
+  #         java-version: ${{ matrix.java }}
+  #     - name: Cache scala dependencies
+  #       uses: coursier/cache-action@v6
 
-      - name: Run JS tests
-        run: |
-          ./mill -i -k -j 0 "morphir[${{matrix.scala}}].__.js.__.compile" + "morphir[${{matrix.scala}}].__.js.publishArtifacts" + "morphir[${{matrix.scala}}].__.js.__.test"
+  #     - name: Run JS tests
+  #       run: |
+  #         ./mill -i -k -j 0 "morphir[${{matrix.scala}}].__.js.__.compile" + "morphir[${{matrix.scala}}].__.js.publishArtifacts" + "morphir[${{matrix.scala}}].__.js.__.test"
 
-      - name: Cache JS build output
-        # when in master repo: all commits to main branch and all additional tags
-        if: github.ref == 'refs/heads/main' || (github.ref != 'refs/heads/main' && startsWith( github.ref, 'refs/tags/') )
-        uses: actions/cache/save@v4
-        with:
-          path: |
-            out/morphir/${{matrix.scala}}/**/js/
-          key: ${{ runner.os }}-mill-js-${{matrix.java}}-${{ matrix.scala }}-${{ github.sha}}-${{ hashFiles('out') }}
+  #     - name: Cache JS build output
+  #       # when in master repo: all commits to main branch and all additional tags
+  #       if: github.ref == 'refs/heads/main' || (github.ref != 'refs/heads/main' && startsWith( github.ref, 'refs/tags/') )
+  #       uses: actions/cache/save@v4
+  #       with:
+  #         path: |
+  #           out/morphir/${{matrix.scala}}/**/js/
+  #         key: ${{ runner.os }}-mill-js-${{matrix.java}}-${{ matrix.scala }}-${{ github.sha}}-${{ hashFiles('out') }}
 
-  test-jvm:
-    runs-on: ubuntu-latest
-    timeout-minutes: 30
-    strategy:
-      fail-fast: false
-      matrix:
-        java: ["11", "17"]
-        scala: ["3.3.3"]
-    steps:
-      - name: Checkout current branch
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
+  # test-jvm:
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 30
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       java: ["11", "17"]
+  #       scala: ["3.3.3"]
+  #   steps:
+  #     - name: Checkout current branch
+  #       uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 0
 
-      - name: Setup Node.js
-        uses: actions/setup-node@v4
-        with:
-          node-version-file: ".nvmrc"
+  #     - name: Setup Node.js
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version-file: ".nvmrc"
 
-      - name: Install morphir-elm
-        run: |
-          npm install -g morphir-elm
+  #     - name: Install morphir-elm
+  #       run: |
+  #         npm install -g morphir-elm
 
-      - name: Setup Scala and Java
-        uses: actions/setup-java@v4
-        with:
-          distribution: "temurin"
-          java-version: ${{ matrix.java }}
-      - name: Cache scala dependencies
-        uses: coursier/cache-action@v6
+  #     - name: Setup Scala and Java
+  #       uses: actions/setup-java@v4
+  #       with:
+  #         distribution: "temurin"
+  #         java-version: ${{ matrix.java }}
+  #     - name: Cache scala dependencies
+  #       uses: coursier/cache-action@v6
 
-      - name: Setup proto and moon toolchains
-        uses: moonrepo/setup-toolchain@v0.3.1
-        with:
-          auto-install: true
+  #     - name: Setup proto and moon toolchains
+  #       uses: moonrepo/setup-toolchain@v0.3.1
+  #       with:
+  #         auto-install: true
 
-      - name: Install tooling
-        run: |
-          ./build.sh install
-      - name: Make Morphir IR
-        run: |
-          ./build.sh run :morphir-elm-build
-      - name: Run JVM tests
-        run: |
-          ./build.sh --scala-version ${{matrix.scala}} test-jvm
+  #     - name: Install tooling
+  #       run: |
+  #         ./build.sh install
+  #     - name: Make Morphir IR
+  #       run: |
+  #         ./build.sh run :morphir-elm-build
+  #     - name: Run JVM tests
+  #       run: |
+  #         ./build.sh --scala-version ${{matrix.scala}} test-jvm
 
-      - name: Cache JVM build output
-        # when in master repo: all commits to main branch and all additional tags
-        if: github.ref == 'refs/heads/main' || (github.ref != 'refs/heads/main' && startsWith( github.ref, 'refs/tags/') )
-        uses: actions/cache/save@v4
-        with:
-          path: |
-            out/morphir/${{matrix.scala}}/**/jvm/
-            out/morphir/build/
-          key: ${{ runner.os }}-mill-jvm-${{matrix.java}}-${{ matrix.scala }}-${{ github.sha }}-${{ hashFiles('out') }}
+  #     - name: Cache JVM build output
+  #       # when in master repo: all commits to main branch and all additional tags
+  #       if: github.ref == 'refs/heads/main' || (github.ref != 'refs/heads/main' && startsWith( github.ref, 'refs/tags/') )
+  #       uses: actions/cache/save@v4
+  #       with:
+  #         path: |
+  #           out/morphir/${{matrix.scala}}/**/jvm/
+  #           out/morphir/build/
+  #         key: ${{ runner.os }}-mill-jvm-${{matrix.java}}-${{ matrix.scala }}-${{ github.sha }}-${{ hashFiles('out') }}
 
   ############### SONATYPE SCAN ###############
   sonatype-scan:
@@ -180,35 +180,35 @@ jobs:
       #     path: depCache/
 
       - name: Sonatype Lifecycle SCA Scan
-        uses: sonatype-nexus-community/iq-github-action@main
+        id: evaluate
+        uses: sonatype/actions/evaluate@v1
         with:
+          iq-server-url: ${{ env.SonatypeUrl }}
           username: ${{ secrets.SONATYPE_USER }}
           password: ${{ secrets.SONATYPE_PASSWORD }}
-          serverUrl: ${{ env.SonatypeUrl }}
-          applicationId: ${{ env.SonatypeAppId }}
+          application-id: ${{ env.SonatypeAppId }}
           stage: ${{ env.SonatypeStage }}
-          target: ${{ env.SonatypeScanTarget }} ${{ env.ExcludeDirectory }}
+          scan-targets: ${{ env.SonatypeScanTarget }} ${{ env.ExcludeDirectory }}
 
       - name: Retrieve Sonatype SBOM (SPDX)
-        if: always()
-        run: |
-          mkdir reports/
-          iqCredentials="${{ secrets.SONATYPE_USER }}:${{ secrets.SONATYPE_PASSWORD }}"
-          echo 'Get internal app ID for public ID: '$SonatypeAppId
-          res=$(curl -u $iqCredentials --location $SonatypeUrl'api/v2/applications?publicId='$SonatypeAppId)
-          IFS='"' read -a array <<< "$res"
-          echo 'Internal app ID: '${array[5]}
-          internalID=${array[5]}
-          curl -u $iqCredentials --location $SonatypeUrl'api/v2/spdx/'$internalID'/stages/'$SonatypeStage -H 'Accept: application/xml' > reports/$SonatypeAppId.spdx.json
-          echo 'Sonatype SBOM (SPDX): '
-          cat reports/$SonatypeAppId.spdx.json
-
-      - name: Upload Sonatype SBOM (SPDX)
-        if: always()
-        uses: actions/upload-artifact@v4
+        uses: sonatype/actions/fetch-sbom@v1
+        if: ( success() || failure() ) && steps.evaluate.outputs.scan-id
         with:
-          name: ${{ env.SonatypeAppId }} Sonatype SBOM (SPDX)
-          path: reports/
+          iq-server-url: ${{ env.SonatypeUrl }}
+          username: ${{ secrets.SONATYPE_USER }}
+          password: ${{ secrets.SONATYPE_PASSWORD }}
+          application-id: ${{ env.SonatypeAppId }}
+          scan-id: ${{ steps.evaluate.outputs.scan-id }}
+          sbom-standard: spdx
+          sbom-version: 2.3
+          artifact-name: ${{ env.SonatypeAppId }}
+
+      # - name: Upload Sonatype SBOM (SPDX)
+      #   if: always()
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: ${{ env.SonatypeAppId }} Sonatype SBOM (SPDX)
+      #     path: reports/
   #############################################
 
   publish:
@@ -281,8 +281,9 @@ jobs:
         run: ./mill -i ci.publishSonatype __.publishArtifacts
 
   ci:
-    runs-on: ubuntu-latest
-    needs: [lint, test-js, test-jvm]
+    runs-on: ubuntu-latest    
+    needs: [lint]
+    # needs: [lint, test-js, test-jvm]
     steps:
       - name: Aggregate of lint, and all tests
         run: echo "ci passed"
