Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -26,31 +26,31 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
-  lint:
-    runs-on: ubuntu-latest
-    timeout-minutes: 30
-    steps:
-      - name: Checkout current branch
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      - name: Setup Scala and Java
-        uses: actions/setup-java@v4
-        with:
-          distribution: "temurin"
-          java-version: "17"
-      - name: Cache scala dependencies
-        uses: coursier/cache-action@v6
-      - name: Setup proto and moon toolchains
-        uses: moonrepo/setup-toolchain@v0.3.1
-        with:
-          auto-install: true
+  # lint:
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 30
+  #   steps:
+  #     - name: Checkout current branch
+  #       uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 0
+  #     - name: Setup Scala and Java
+  #       uses: actions/setup-java@v4
+  #       with:
+  #         distribution: "temurin"
+  #         java-version: "17"
+  #     - name: Cache scala dependencies
+  #       uses: coursier/cache-action@v6
+  #     - name: Setup proto and moon toolchains
+  #       uses: moonrepo/setup-toolchain@v0.3.1
+  #       with:
+  #         auto-install: true
             
-      - name: Install tooling
-        run: |
-          ./build.sh install
-      - name: Lint code
-        run: ./build.sh lint
+  #     - name: Install tooling
+  #       run: |
+  #         ./build.sh install
+  #     - name: Lint code
+  #       run: ./build.sh lint
 
   test-js:
     runs-on: ubuntu-latest
@@ -86,96 +86,93 @@ jobs:
             out/morphir/${{matrix.scala}}/**/js/
           key: ${{ runner.os }}-mill-js-${{matrix.java}}-${{ matrix.scala }}-${{ github.sha}}-${{ hashFiles('out') }}
 
-  test-jvm:
-    runs-on: ubuntu-latest
-    timeout-minutes: 30
-    strategy:
-      fail-fast: false
-      matrix:
-        java: ["11", "17"]
-        scala: ["2.13.13", "3.3.3"]
-    steps:
-      - name: Checkout current branch
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      - name: Setup Scala and Java
-        uses: actions/setup-java@v4
-        with:
-          distribution: "temurin"
-          java-version: ${{ matrix.java }}
-      - name: Cache scala dependencies
-        uses: coursier/cache-action@v6
+      - run: find . 
 
-      # - name: MILL
-      #   run: |
-      #     ./mill resolve __.ivyDepsTree
-      #     ./mill resolve morphir[${{ matrix.scala }}].jvm.ivyDepsTree
+  # test-jvm:
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 30
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       java: ["11", "17"]
+  #       scala: ["2.13.13", "3.3.3"]
+  #   steps:
+  #     - name: Checkout current branch
+  #       uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 0
+  #     - name: Setup Scala and Java
+  #       uses: actions/setup-java@v4
+  #       with:
+  #         distribution: "temurin"
+  #         java-version: ${{ matrix.java }}
+  #     - name: Cache scala dependencies
+  #       uses: coursier/cache-action@v6
 
-      - name: Setup proto and moon toolchains
-        uses: moonrepo/setup-toolchain@v0.3.1
-        with:
-          auto-install: true
+      # - name: Setup proto and moon toolchains
+      #   uses: moonrepo/setup-toolchain@v0.3.1
+      #   with:
+      #     auto-install: true
             
-      - name: Install tooling
-        run: |
-          ./build.sh install
-      - name: Make Morphir IR
-        run: |
-          ./build.sh run :morphir-elm-build
-      - name: Run JVM tests
-        run: |
-          ./build.sh --scala-version ${{matrix.scala}} test-jvm
+      # - name: Install tooling
+      #   run: |
+      #     ./build.sh install
+      # - name: Make Morphir IR
+      #   run: |
+      #     ./build.sh run :morphir-elm-build
+      # - name: Run JVM tests
+      #   run: |
+      #     ./build.sh --scala-version ${{matrix.scala}} test-jvm
 
-      - name: Cache JVM build output
-        # when in master repo: all commits to main branch and all additional tags
-        if: github.ref == 'refs/heads/main' || (github.ref != 'refs/heads/main' && startsWith( github.ref, 'refs/tags/') )
-        uses: actions/cache/save@v4
-        with:
-          path: |
-            out/morphir/${{matrix.scala}}/**/jvm/
-            out/morphir/build/
-          key: ${{ runner.os }}-mill-jvm-${{matrix.java}}-${{ matrix.scala }}-${{ github.sha }}-${{ hashFiles('out') }}
+      # - name: Cache JVM build output
+      #   # when in master repo: all commits to main branch and all additional tags
+      #   if: github.ref == 'refs/heads/main' || (github.ref != 'refs/heads/main' && startsWith( github.ref, 'refs/tags/') )
+      #   uses: actions/cache/save@v4
+      #   with:
+      #     path: |
+      #       out/morphir/${{matrix.scala}}/**/jvm/
+      #       out/morphir/build/
+      #     key: ${{ runner.os }}-mill-jvm-${{matrix.java}}-${{ matrix.scala }}-${{ github.sha }}-${{ hashFiles('out') }}
           
-  test-native:
-    runs-on: ubuntu-latest
-    timeout-minutes: 30
-    strategy:
-      fail-fast: false
-      matrix:
-        java: ["11"] # Note there is no need ro actually run this for multiple JVM versions for native
-        scala: ["2.13.13", "3.3.3"]
-    steps:
-      - name: Checkout current branch
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      - name: Install libuv
-        run: sudo apt-get update && sudo apt-get install -y libuv1-dev
+  # test-native:
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 30
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       java: ["11"] # Note there is no need ro actually run this for multiple JVM versions for native
+  #       scala: ["2.13.13", "3.3.3"]
+  #   steps:
+  #     - name: Checkout current branch
+  #       uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 0
+  #     - name: Install libuv
+  #       run: sudo apt-get update && sudo apt-get install -y libuv1-dev
 
-      - name: Set up Clang
-        uses: egor-tensin/setup-clang@v1
-        with:
-          version: latest
-          platform: x64
-      - name: Setup Scala and Java
-        uses: actions/setup-java@v4
-        with:
-          distribution: "temurin"
-          java-version: ${{ matrix.java }}
+  #     - name: Set up Clang
+  #       uses: egor-tensin/setup-clang@v1
+  #       with:
+  #         version: latest
+  #         platform: x64
+  #     - name: Setup Scala and Java
+  #       uses: actions/setup-java@v4
+  #       with:
+  #         distribution: "temurin"
+  #         java-version: ${{ matrix.java }}
 
-      - name: Run Native tests
-        run: |
-          ./mill -i -k -j 0 "morphir[${{matrix.scala}}].__.native.__.compile" + "morphir[${{matrix.scala}}].__.native.publishArtifacts" + "morphir[${{matrix.scala}}].__.native.__.test"
+  #     - name: Run Native tests
+  #       run: |
+  #         ./mill -i -k -j 0 "morphir[${{matrix.scala}}].__.native.__.compile" + "morphir[${{matrix.scala}}].__.native.publishArtifacts" + "morphir[${{matrix.scala}}].__.native.__.test"
 
-      - name: Cache Native build output
-        # when in master repo: all commits to main branch and all additional tags
-        if: github.ref == 'refs/heads/main' || (github.ref != 'refs/heads/main' && startsWith( github.ref, 'refs/tags/') )
-        uses: actions/cache/save@v4
-        with:
-          path: |
-            out/morphir/${{matrix.scala}}/**/native/
-          key: ${{ runner.os }}-mill-native-${{matrix.java}}-${{ matrix.scala }}-${{ github.sha }}-${{ hashFiles('out') }}
+  #     - name: Cache Native build output
+  #       # when in master repo: all commits to main branch and all additional tags
+  #       if: github.ref == 'refs/heads/main' || (github.ref != 'refs/heads/main' && startsWith( github.ref, 'refs/tags/') )
+  #       uses: actions/cache/save@v4
+  #       with:
+  #         path: |
+  #           out/morphir/${{matrix.scala}}/**/native/
+  #         key: ${{ runner.os }}-mill-native-${{matrix.java}}-${{ matrix.scala }}-${{ github.sha }}-${{ hashFiles('out') }}
 
 
   ############### SONATYPE SCAN ###############
@@ -186,6 +183,12 @@ jobs:
     steps:
     - name: Cache scala dependencies
       uses: coursier/cache-action@v6
+
+    - name: Get OUT cache
+      uses: actions/cache/restore@v4
+      with:
+        path: out/
+        key: ${{ runner.os }}-*
         
     - name: Copy Cache for SCA Scan
       run: |
